parameters:
services:
    #FORMS
    odiseo_sylius_blog.extension.type.article:
        class: Odiseo\SyliusBlogPlugin\Form\Extension\ArticleTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Odiseo\BlogBundle\Form\Type\ArticleType }

    #LISTENERS
    odiseo_sylius_blog.listener.admin.menu_builder:
        class: Odiseo\SyliusBlogPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }