parameters:
services:
    odiseo_sylius_blog.factory.article_comment:
        class: Odiseo\SyliusBlogPlugin\Factory\ArticleCommentFactory
        decorates: odiseo_blog.factory.article_comment
        arguments: ['@odiseo_sylius_blog.factory.article_comment.inner', '@security.token_storage']
        public: false

    #FORMS
    odiseo_sylius_blog.extension.type.article:
        class: Odiseo\SyliusBlogPlugin\Form\Extension\ArticleTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Odiseo\BlogBundle\Form\Type\ArticleType }

    odiseo_sylius_blog.extension.type.article_user_comment:
        class: Odiseo\SyliusBlogPlugin\Form\Extension\ArticleUserCommentTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Odiseo\BlogBundle\Form\Type\ArticleUserCommentType }

    #LISTENERS
    odiseo_sylius_blog.listener.admin.menu_builder:
        class: Odiseo\SyliusBlogPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    #FIXTURES
    odiseo_sylius_blog.fixture.blog:
        class: Odiseo\SyliusBlogPlugin\Fixture\BlogFixture
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@odiseo_blog.factory.article"
            - "@odiseo_blog.factory.article_category"
            - "@odiseo_blog.factory.article_image"
            - "@odiseo_blog.factory.article_comment"
            - "@sylius.repository.channel"
            - "@sylius.repository.locale"
            - "@odiseo_blog.listener.article_image_upload"
        tags:
            - { name: "sylius_fixtures.fixture" }
