Odiseo\SyliusBlogPlugin\Model\Article:
    type: mappedSuperclass
    table: odiseo_blog_article
    manyToMany:
        channels:
            targetEntity: Sylius\Component\Channel\Model\ChannelInterface
            joinTable:
                name: odiseo_blog_articles_channels
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    channel_id:
                        referencedColumnName: id
    manyToOne:
        author:
            targetEntity: Sylius\Component\Core\Model\AdminUserInterface
            joinColumn:
                name: author_id
                referencedColumnName: id
